services:
  sensor-server:
    build: .
    ports:
      - "8080:8080"   # WebSocket port
      - "1234:1234/udp"  # UDP port
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:${WS_PORT:-8080}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
